import * as fs from "node:fs/promises";
import * as path from "node:path";

const CHECK_BYTE_COUNT = 1024;
const HEADER_LINE_LIMIT = 40;

const KNOWN_GENERATOR_PATTERN =
	"(?:protoc(?:-gen-[\\w-]+)?|sqlc|buf|swagger(?:-codegen)?|openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)";

const AUTO_GENERATED_HEADER_MARKERS: readonly RegExp[] = [
	/@generated\b/i,
	/\bcode\s+generated\s+by\s+[a-z0-9_.-]+/i,
	/\bthis\s+file\s+was\s+automatically\s+generated\b/i,
	new RegExp(`\\bgenerated\\s+by\\s+${KNOWN_GENERATOR_PATTERN}\\b`, "i"),
];

const AUTO_GENERATED_FILENAME_PATTERNS: readonly RegExp[] = [
	/^zz_generated\./,
	/\.pb\.(go|cc|h|c|js|ts)$/,
	/_pb2\.py$/,
	/_pb2_grpc\.py$/,
	/\.gen\.(go|ts|js|py)$/,
	/^generated\.(go|ts|js|py)$/,
	/\.swagger\.json$/,
	/\.openapi\.json$/,
	/\.mock\.(go|ts)$/,
	/\.mocks?\.(go|ts|js)$/,
];

type CommentStyle = "slash" | "hash" | "sql" | "html";

const COMMENT_STYLES_BY_EXTENSION = new Map<string, readonly CommentStyle[]>([
	[".c", ["slash"]], [".cc", ["slash"]], [".cpp", ["slash"]], [".cs", ["slash"]], [".dart", ["slash"]],
	[".go", ["slash"]], [".h", ["slash"]], [".hpp", ["slash"]], [".java", ["slash"]], [".js", ["slash"]],
	[".jsx", ["slash"]], [".kt", ["slash"]], [".kts", ["slash"]], [".mjs", ["slash"]], [".cjs", ["slash"]],
	[".php", ["slash"]], [".rs", ["slash"]], [".scala", ["slash"]], [".swift", ["slash"]], [".ts", ["slash"]],
	[".tsx", ["slash"]], [".py", ["hash"]], [".rb", ["hash"]], [".sh", ["hash"]], [".bash", ["hash"]],
	[".zsh", ["hash"]], [".yml", ["hash"]], [".yaml", ["hash"]], [".toml", ["hash"]], [".ini", ["hash"]],
	[".cfg", ["hash"]], [".conf", ["hash"]], [".env", ["hash"]], [".pl", ["hash"]], [".r", ["hash"]],
	[".sql", ["sql"]], [".html", ["html"]], [".htm", ["html"]], [".xml", ["html"]], [".svg", ["html"]],
	[".xhtml", ["html"]],
]);

const COMMENT_STYLES_BY_BASENAME = new Map<string, readonly CommentStyle[]>([
	["dockerfile", ["hash"]],
	["makefile", ["hash"]],
	["justfile", ["hash"]],
]);

const HASHLINE_PREFIX_RE = /^\s*(?:>>>|>>)?\s*(?:\+?\s*(?:\d+\s*#\s*|#\s*)|\+)\s*[ZPMQVRWSNKTXJBYH]{2}:/;

export function stripHashlinePrefixes(content: string): { text: string; stripped: boolean } {
	const lines = content.split("\n");
	let nonEmpty = 0;
	let matchCount = 0;
	for (const line of lines) {
		if (line.length === 0) continue;
		nonEmpty++;
		if (HASHLINE_PREFIX_RE.test(line)) matchCount++;
	}
	if (nonEmpty === 0 || matchCount !== nonEmpty) return { text: content, stripped: false };
	return { text: lines.map((line) => (line.length === 0 ? line : line.replace(HASHLINE_PREFIX_RE, ""))).join("\n"), stripped: true };
}

export async function assertLocalEditableFile(absolutePath: string, displayPath: string): Promise<void> {
	let marker: string | undefined;
	if (isAutoGeneratedFileName(absolutePath)) marker = `filename pattern: ${path.basename(absolutePath)}`;
	else {
		try {
			const handle = await fs.open(absolutePath, "r");
			try {
				const buf = Buffer.alloc(CHECK_BYTE_COUNT);
				const { bytesRead } = await handle.read(buf, 0, CHECK_BYTE_COUNT, 0);
				marker = detectAutoGeneratedMarker(buf.toString("utf8", 0, bytesRead), absolutePath);
			} finally {
				await handle.close();
			}
		} catch (error: any) {
			if (error?.code === "ENOENT") return;
			throw error;
		}
	}
	assertNoGeneratedMarker(marker, displayPath);
}

export function assertRemoteEditableContent(remotePath: string, existingPrefix: string | undefined): void {
	const marker = isAutoGeneratedFileName(remotePath)
		? `filename pattern: ${remotePath.split("/").pop()}`
		: existingPrefix === undefined
			? undefined
			: detectAutoGeneratedMarker(existingPrefix, remotePath);
	assertNoGeneratedMarker(marker, remotePath);
}

function assertNoGeneratedMarker(marker: string | undefined, displayPath: string): void {
	if (!marker) return;
	throw new Error(
		`Cannot modify auto-generated file: ${displayPath}\n\n` +
		`This file appears to be automatically generated (detected: "${marker}").\n` +
		"Auto-generated files should not be edited directly. Instead:\n" +
		"1. Find the source file or generator configuration\n" +
		"2. Make changes to the source\n" +
		"3. Regenerate the file",
	);
}

function detectAutoGeneratedMarker(content: string, filePath: string): string | undefined {
	const headerText = extractLeadingHeaderCommentText(content, getCommentStylesForPath(filePath));
	if (!headerText) return undefined;
	for (const pattern of AUTO_GENERATED_HEADER_MARKERS) {
		const match = pattern.exec(headerText);
		if (match?.[0]) return match[0];
	}
	return undefined;
}

function getCommentStylesForPath(filePath: string): readonly CommentStyle[] {
	const normalizedPath = filePath.toLowerCase();
	const fileName = path.basename(normalizedPath);
	return COMMENT_STYLES_BY_BASENAME.get(fileName) ?? COMMENT_STYLES_BY_EXTENSION.get(path.extname(fileName)) ?? [];
}

function extractLeadingHeaderCommentText(content: string, commentStyles: readonly CommentStyle[]): string {
	if (commentStyles.length === 0) return "";
	const includeSlash = commentStyles.includes("slash");
	const includeHash = commentStyles.includes("hash");
	const includeSql = commentStyles.includes("sql");
	const includeHtml = commentStyles.includes("html");
	const lines = stripBom(content).split(/\r?\n/);
	const headerLines: string[] = [];
	let started = false;
	let inSlashBlock = false;
	let inHtmlBlock = false;
	for (let i = 0; i < lines.length && i < HEADER_LINE_LIMIT; i++) {
		const trimmed = lines[i]?.trim() ?? "";
		if (i === 0 && trimmed.startsWith("#!")) continue;
		if (inSlashBlock) { headerLines.push(trimmed); if (trimmed.includes("*/")) inSlashBlock = false; continue; }
		if (inHtmlBlock) { headerLines.push(trimmed); if (trimmed.includes("-->")) inHtmlBlock = false; continue; }
		if (trimmed.length === 0) { if (started) headerLines.push(""); continue; }
		if (includeSlash && trimmed.startsWith("//")) { started = true; headerLines.push(trimmed); continue; }
		if (includeSlash && trimmed.startsWith("/*")) { started = true; headerLines.push(trimmed); if (!trimmed.includes("*/")) inSlashBlock = true; continue; }
		if (includeHash && trimmed.startsWith("#")) { started = true; headerLines.push(trimmed); continue; }
		if (includeSql && trimmed.startsWith("--")) { started = true; headerLines.push(trimmed); continue; }
		if (includeHtml && trimmed.startsWith("<!--")) { started = true; headerLines.push(trimmed); if (!trimmed.includes("-->")) inHtmlBlock = true; continue; }
		break;
	}
	return headerLines.join("\n");
}

function isAutoGeneratedFileName(filePath: string): boolean {
	const fileName = filePath.split("/").pop() ?? "";
	return AUTO_GENERATED_FILENAME_PATTERNS.some((pattern) => pattern.test(fileName));
}

function stripBom(content: string): string {
	return content.charCodeAt(0) === 0xfeff ? content.slice(1) : content;
}
